//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFarmingProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbMyEFarmingProjectEntities : DbContext
    {
        public dbMyEFarmingProjectEntities()
            : base("name=dbMyEFarmingProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Category> Tbl_Category { get; set; }
        public virtual DbSet<Tbl_District> Tbl_District { get; set; }
        public virtual DbSet<Tbl_NidType> Tbl_NidType { get; set; }
        public virtual DbSet<Tbl_SellerProduct> Tbl_SellerProduct { get; set; }
        public virtual DbSet<Tbl_Support> Tbl_Support { get; set; }
        public virtual DbSet<Tbl_BuyerProfile> Tbl_BuyerProfile { get; set; }
        public virtual DbSet<Tbl_Product> Tbl_Product { get; set; }
        public virtual DbSet<UsersRole> UsersRole { get; set; }
        public virtual DbSet<Tbl_Blog> Tbl_Blog { get; set; }
        public virtual DbSet<Tbl_Comment> Tbl_Comment { get; set; }
    }
}
