//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFarmingProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_SellerProduct
    {
        public int SProductId { get; set; }
        public Nullable<int> BId { get; set; }
        public string SProductTitle { get; set; }
        public string SProductDescription { get; set; }
        public string SProductImage { get; set; }
        public Nullable<int> SQuantity { get; set; }
        public Nullable<int> SPrice { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<System.DateTime> SCreatedDate { get; set; }
        public Nullable<System.DateTime> SModifiedDate { get; set; }
        public Nullable<bool> IsAdminApproved { get; set; }
    
        public virtual Tbl_Category Tbl_Category { get; set; }
        public virtual Tbl_BuyerProfile Tbl_BuyerProfile { get; set; }
    }
}
