//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFarmingProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_BuyerProfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_BuyerProfile()
        {
            this.Tbl_SellerProduct = new HashSet<Tbl_SellerProduct>();
            this.Tbl_Support = new HashSet<Tbl_Support>();
            this.Tbl_Product = new HashSet<Tbl_Product>();
            this.UsersRole = new HashSet<UsersRole>();
            this.Tbl_Comment = new HashSet<Tbl_Comment>();
        }
    
        public int BId { get; set; }
        public string BFirstName { get; set; }
        public string BLastName { get; set; }
        public string BEmailId { get; set; }
        public string BNidNo { get; set; }
        public Nullable<System.DateTime> BDateOfBirth { get; set; }
        public string BPassword { get; set; }
        public bool BIsEmailVarified { get; set; }
        public System.Guid BActivationCode { get; set; }
        public string BDescription { get; set; }
        public Nullable<int> NidTypeId { get; set; }
        public string BImage { get; set; }
        public Nullable<System.DateTime> BCreatedDate { get; set; }
        public Nullable<System.DateTime> BModifiedDate { get; set; }
        public Nullable<bool> IsBuyer { get; set; }
        public Nullable<bool> IsSeller { get; set; }
        public string ResetPasswordCode { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> MobileNo { get; set; }
        public Nullable<int> AnotherMobileNo { get; set; }
        public Nullable<int> Postcode { get; set; }
        public string Thana { get; set; }
        public string Division { get; set; }
        public string Village { get; set; }
        public Nullable<bool> IsBuyerActivated { get; set; }
        public Nullable<bool> IsSellerActivated { get; set; }
    
        public virtual Tbl_District Tbl_District { get; set; }
        public virtual Tbl_NidType Tbl_NidType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_SellerProduct> Tbl_SellerProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Support> Tbl_Support { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Product> Tbl_Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersRole> UsersRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Comment> Tbl_Comment { get; set; }
    }
}
