//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFarmingProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_NidType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_NidType()
        {
            this.Tbl_BuyerProfile = new HashSet<Tbl_BuyerProfile>();
        }
    
        public int NidTypeId { get; set; }
        public string NidType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_BuyerProfile> Tbl_BuyerProfile { get; set; }
    }
}
