//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFarmingProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Comment
    {
        public int CommentID { get; set; }
        public string CommentName { get; set; }
        public Nullable<System.DateTime> CommentDate { get; set; }
        public string CommentTitle { get; set; }
        public Nullable<int> BLogId { get; set; }
        public Nullable<int> BId { get; set; }
    
        public virtual Tbl_Blog Tbl_Blog { get; set; }
        public virtual Tbl_BuyerProfile Tbl_BuyerProfile { get; set; }
    }
}
