//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFarmingProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Product
    {
        public int ProductId { get; set; }
        public string ProductTitle { get; set; }
        public string ProductDescription { get; set; }
        public string ProductImage { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsFeatured { get; set; }
        public Nullable<int> BId { get; set; }
    
        public virtual Tbl_BuyerProfile Tbl_BuyerProfile { get; set; }
        public virtual Tbl_Category Tbl_Category { get; set; }
    }
}
